// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bavlclbawygaqqhuovvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdmxjbGJhd3lnYXFxaHVvdnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTk3NjMsImV4cCI6MjA2NTkzNTc2M30.48KaKUhW-V3nKj4oIVe6GhrToUbVlRKX84rbY91Y8Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);